---
# ServiceAccount for Auth Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: services

---
# ServiceAccount for Merchant Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: merchant-service
  namespace: services

---
# ServiceAccount for Payment API Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api-service
  namespace: services

---
# ServiceAccount for Tokenization Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tokenization-service
  namespace: internal

---
# ServiceAccount for Transaction Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-service
  namespace: internal

---
# ServiceAccount for Database Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-service
  namespace: databases