# -------------------------
# Merchant Service
# -------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-service
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merchant-service
  template:
    metadata:
      labels:
        app: merchant-service
    spec:
      containers:
      - name: merchant-service
        image: rhaloubi8/payment-gateway-merchant:latest
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
        - name: APP_MODE
          value: "production"
        - name: DATABASE_DSN
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: merchant-dsn
        - name: REDIS_DSN
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: redis-dsn
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.services.svc.cluster.local:8001"
        - name: AUTH_SERVICE_GRPC_URL
          value: "auth-service.services.svc.cluster.local:50051"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: GIN_MODE
          value: "release"
        - name: MAILTRAP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mailtrap-username
        - name: MAILTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mailtrap-password
        - name: MAILTRAP_HOST
          value: "smtp.mailtrap.io"
        - name: MAILTRAP_PORT
          value: "2525"
        - name: FROM_EMAIL
          value: "redahaloubi8@gmail.com"
        - name: FROM_NAME
          value: "Payment Gateway"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 40
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: merchant-service
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: merchant-service
  ports:
  - port: 8002
    targetPort: 8002
