# -------------------------
# ServiceAccount
# -------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api-service
  namespace: services
---
# -------------------------
# Payment API Service
# -------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api-service
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api-service
  template:
    metadata:
      labels:
        app: payment-api-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-init: "false"
        vault.hashicorp.com/role: "payment-api-service"
        vault.hashicorp.com/agent-pre-populate-only: "false"

        # Resource limits for Vault Agent
        vault.hashicorp.com/agent-requests-cpu: "25m"
        vault.hashicorp.com/agent-limits-cpu: "50m"
        vault.hashicorp.com/agent-requests-mem: "64Mi"
        vault.hashicorp.com/agent-limits-mem: "128Mi"
        vault.hashicorp.com/agent-init-requests-cpu: "25m"
        vault.hashicorp.com/agent-init-limits-cpu: "50m"

        # DATABASE DSN
        vault.hashicorp.com/agent-inject-secret-payment-api-dsn: "secret/data/database/payment-api-dsn"
        vault.hashicorp.com/agent-inject-template-payment-api-dsn: |
          {{- with secret "secret/data/database/payment-api-dsn" -}}
          {{ .Data.data.value }}
          {{- end }}

        # REDIS DSN
        vault.hashicorp.com/agent-inject-secret-redis-dsn: "secret/data/database/redis-dsn"
        vault.hashicorp.com/agent-inject-template-redis-dsn: |
          {{- with secret "secret/data/database/redis-dsn" -}}
          {{ .Data.data.value }}
          {{- end }}

        # CHECKOUT URL
        vault.hashicorp.com/agent-inject-secret-checkout-url: "secret/data/app/checkout-url"
        vault.hashicorp.com/agent-inject-template-checkout-url: |
          {{- with secret "secret/data/app/checkout-url" -}}
          {{ .Data.data.value }}
          {{- end }}
    spec:
      serviceAccountName: payment-api-service
      containers:
      - name: payment-api-service
        image: rhaloubi8/payment-gateway-payment-api:latest
        ports:
        - containerPort: 8004
        env:
        - name: PORT
          value: "8004"
        - name: APP_MODE
          value: "production"
        - name: DATABASE_DSN_FILE
          value: "/vault/secrets/payment-api-dsn"
        - name: REDIS_DSN_FILE
          value: "/vault/secrets/redis-dsn"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.services:8001"
        - name: TOKENIZATION_SERVICE_GRPC_URL
          value: "tokenization-service.internal:50052"
        - name: TRANSACTION_SERVICE_GRPC_URL
          value: "transaction-service.internal:50053"
        - name: AUTH_SERVICE_GRPC_URL
          value: "auth-service.services:50051"
        - name: GIN_MODE
          value: "release"
        - name: CHECKOUT_URL_FILE
          value: "/vault/secrets/checkout-url"
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 40
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: payment-api-service
  ports:
  - port: 8004
    targetPort: 8004