# -------------------------
# Tokenization Service
# -------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenization-service
  namespace: internal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tokenization-service
  template:
    metadata:
      labels:
        app: tokenization-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "tokenization-service"
        vault.hashicorp.com/agent-inject-env: "VAULT_ADDR"
        vault.hashicorp.com/agent-inject-secret-tokenization-dsn: "secret/data/database/tokenization-dsn"
        vault.hashicorp.com/agent-inject-template-tokenization-dsn: |
          {{- with secret "secret/data/database/tokenization-dsn" -}}
          {{ .Data.data.value }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-redis-dsn: "secret/data/database/redis-dsn"
        vault.hashicorp.com/agent-inject-template-redis-dsn: |
          {{- with secret "secret/data/database/redis-dsn" -}}
          {{ .Data.data.value }}
          {{- end }}
    spec:
      serviceAccountName: tokenization-service
      containers:
      - name: tokenization-service
        image: rhaloubi8/payment-gateway-tokenization:latest
        ports:
        - containerPort: 50052
        env:
        - name: GRPC_PORT
          value: "50052"
        - name: APP_MODE
          value: "production"
        - name: DATABASE_DSN
          value: "file:///vault/secrets/tokenization-dsn"
        - name: REDIS_DSN
          value: "file:///vault/secrets/redis-dsn"
        - name: GIN_MODE
          value: "release"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.services:8001"
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tokenization-service
  namespace: internal
spec:
  type: ClusterIP
  selector:
    app: tokenization-service
  ports:
  - port: 50052
    targetPort: 50052
