# -------------------------
# Transaction Service
# -------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: internal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transaction-service"
        vault.hashicorp.com/agent-inject-env: "VAULT_ADDR"
        vault.hashicorp.com/agent-inject-secret-transaction-dsn: "secret/data/database/transaction-dsn"
        vault.hashicorp.com/agent-inject-template-transaction-dsn: |
          {{- with secret "secret/data/database/transaction-dsn" -}}
          {{ .Data.data.value }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-redis-dsn: "secret/data/database/redis-dsn"
        vault.hashicorp.com/agent-inject-template-redis-dsn: |
          {{- with secret "secret/data/database/redis-dsn" -}}
          {{ .Data.data.value }}
          {{- end }}  
    spec:
      serviceAccountName: transaction-service
      containers:
      - name: transaction-service
        image: rhaloubi8/payment-gateway-transaction:latest
        ports:
        - containerPort: 50053
        env:
        - name: GRPC_PORT
          value: "50053"
        - name: APP_MODE
          value: "production"
        - name: DATABASE_DSN
          value: "file:///vault/secrets/transaction-dsn"
        - name: REDIS_DSN
          value: "file:///vault/secrets/redis-dsn"
        - name: TOKENIZATION_SERVICE_GRPC
          value: "tokenization-service.internal:50052"
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: GIN_MODE
          value: "release"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: internal
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
  - port: 50053
    targetPort: 50053
